modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/Luke100000/ImmersiveArmors/issues"
license = "GNU"

[[mods]]
modId = "immersive_armors"
version = "${version}"
displayName = "Immersive Armors"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ImmersiveArmors"
authors = "Luke100000"
description = '''
    A lot of unique and vanilla-faithful armor sets.
    '''
logoFile = "logoFile.png"
itemIcon = "immersive_armors:divine_chestplate"

[[dependencies.immersive_armors]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_armors]]
modId = "forge"
mandatory = true
versionRange = "[44.0.30,)"
ordering = "NONE"
side = "BOTH"
